/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import baseDatos.Conexion;
import baseDatos.Consultas;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
//import sun.swing.SwingAccessor;

/**
 *
 * @author MickyOr
 */
public class InformacionExpositores extends javax.swing.JFrame {

    /**
     * Creates new form InformacionExpositores
     */
    
    
    Consultas con;
    
    private ArrayList<String> nombres, apellidos;
    
    // Llena los arraylists con informacion de la base de datos
    private void llenarArrayListsConNombres(){
        ResultSet rs = con.obtenerNombreApellidoDeExpositores();
        nombres = new ArrayList<String>();
        apellidos = new ArrayList<String>();
        try{
            while ( rs.next() ){
                String nombre, apellido;
                nombre = rs.getString("nombre_expo");
                apellido = rs.getString("apellido_expo");
                nombres.add( nombre );
                apellidos.add( apellido );
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Llena el jComboBox con nombres y apellidos
    private void llenarJComboBox(){
        for (int i = 0; i < nombres.size(); i++){
            String item;
            item = nombres.get(i) + " " + apellidos.get(i);
            jComboBoxNombresExpositores.addItem(item);
        }
    }
    
    public InformacionExpositores(Consultas co) {
        initComponents();
        this.setLocationRelativeTo(null);
        con = co;
        llenarArrayListsConNombres();
        llenarJComboBox();
        AutoCompleteDecorator.decorate(jComboBoxNombresExpositores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxNombresExpositores = new javax.swing.JComboBox<>();
        botonObtenerInformacion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(jComboBoxNombresExpositores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 36));

        botonObtenerInformacion.setText("Info. Contacto");
        botonObtenerInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonObtenerInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonObtenerInformacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonObtenerInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 112, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atrás");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("src/ImagenesInterfaces/FondoAzul.jpg"));
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 400, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonObtenerInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonObtenerInformacionActionPerformed
        int index = jComboBoxNombresExpositores.getSelectedIndex();
        String nombre = nombres.get(index);
        String apellido = apellidos.get(index);
        
        System.out.println("nombres: " + nombre + ", " + apellido);
        
        ResultSet rs = con.contactoExpositor(nombre, apellido);
        try{
            rs.last();
            String nro_contacto = rs.getString("nro_contacto");
            
            // Mensaje con la informacion de contacto del expositor
            JOptionPane.showMessageDialog(null, nro_contacto);
        }
        catch(SQLException ex){
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonObtenerInformacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListaInformes interfaz = new ListaInformes(con);
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionExpositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionExpositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionExpositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionExpositores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new InformacionExpositores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonObtenerInformacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxNombresExpositores;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
