/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Edgar Ruben B
 */
public class InscripcionYCancelacion extends javax.swing.JFrame {

    /**
     * Creates new form IncripcionYCancelacion
     */
    public InscripcionYCancelacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabelTriste = new javax.swing.JLabel();
        jLabelFeliz = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setBackground(new java.awt.Color(102, 102, 255));
        jButtonVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar Inscripción");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButtonCancelar1.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCancelar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar1.setText("Inscribir Asistente");
        jButtonCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabelTriste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTriste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaces/CaraTriste1.png"))); // NOI18N
        jLabelTriste.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelTriste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTriste.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelTristeMouseMoved(evt);
            }
        });
        jLabelTriste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTristeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTristeMouseExited(evt);
            }
        });
        getContentPane().add(jLabelTriste, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 180, 210));

        jLabelFeliz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeliz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaces/Muchos.png"))); // NOI18N
        jLabelFeliz.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelFeliz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFeliz.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelFelizMouseMoved(evt);
            }
        });
        jLabelFeliz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFelizMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelFelizMouseExited(evt);
            }
        });
        getContentPane().add(jLabelFeliz, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 190, 210));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaces/FondoAzul.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 275));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jLabelFelizMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFelizMouseMoved
        jLabelFeliz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabelFelizMouseMoved

    private void jLabelFelizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFelizMouseExited
        jLabelFeliz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,51,102)));
    }//GEN-LAST:event_jLabelFelizMouseExited

    private void jLabelTristeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTristeMouseMoved
        jLabelTriste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabelTristeMouseMoved

    private void jLabelTristeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTristeMouseExited
        jLabelTriste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,51,102)));
    }//GEN-LAST:event_jLabelTristeMouseExited

    private void jLabelFelizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFelizMouseClicked
        IngresarDatos id= new IngresarDatos();
        id.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelFelizMouseClicked

    private void jLabelTristeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTristeMouseClicked
        CancelarInscripcion ci= new CancelarInscripcion();
        ci.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelTristeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscripcionYCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscripcionYCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscripcionYCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscripcionYCancelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscripcionYCancelacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelFeliz;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTriste;
    // End of variables declaration//GEN-END:variables
}
